package vista;

import com.sun.awt.AWTUtilities; //LIBRERIA PARA QUE SE MUEVA LA VENTANA
import java.awt.Color;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextArea;

public class vista extends javax.swing.JFrame {

    private boolean modo_oscuro = true;
    private int x, y; //PARA QUE LA VENTANA SE MUEVA
    private String operador;
    private float primer_dato, segundo_dato, resultado;

    public vista() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false); //PARA QUE LA VENTANA SE MUEVA
    }

    public void Generar_Texto(String texto) {
        this.pantalla_grande.setText(this.pantalla_grande.getText() + texto);
        this.pantalla_pequena.setText(this.pantalla_pequena.getText() + texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zona_pantalla = new javax.swing.JPanel();
        boton_modo_oscuro = new javax.swing.JButton();
        boton_minimizar = new javax.swing.JLabel();
        boton_salir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla_pequena = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantalla_grande = new javax.swing.JTextArea();
        mover_ventana = new javax.swing.JLabel();
        zona_botones = new javax.swing.JPanel();
        boton_resta = new javax.swing.JButton();
        boton_borrar_todo = new javax.swing.JButton();
        boton_borrar2 = new javax.swing.JButton();
        boton_porcentaje = new javax.swing.JButton();
        boton_division = new javax.swing.JButton();
        boton_igual = new javax.swing.JButton();
        boton_multiplicacion = new javax.swing.JButton();
        boton_suma = new javax.swing.JButton();
        programador = new javax.swing.JLabel();
        boton_siete = new javax.swing.JButton();
        boton_nueve = new javax.swing.JButton();
        boton_ocho = new javax.swing.JButton();
        boton_seis = new javax.swing.JButton();
        boton_tres = new javax.swing.JButton();
        boton_cinco = new javax.swing.JButton();
        boton_cuatro1 = new javax.swing.JButton();
        boton_punto = new javax.swing.JButton();
        boton_dos = new javax.swing.JButton();
        boton_uno1 = new javax.swing.JButton();
        boton_cero1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zona_pantalla.setBackground(new java.awt.Color(241, 253, 251));
        zona_pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_modo_oscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Barra_de_dia.png"))); // NOI18N
        boton_modo_oscuro.setOpaque(false);
        boton_modo_oscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modo_oscuroActionPerformed(evt);
            }
        });
        zona_pantalla.add(boton_modo_oscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 20));

        boton_minimizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton_minimizar.setForeground(new java.awt.Color(255, 204, 102));
        boton_minimizar.setText("•");
        boton_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_minimizarMouseExited(evt);
            }
        });
        zona_pantalla.add(boton_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        boton_salir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton_salir.setForeground(new java.awt.Color(255, 51, 51));
        boton_salir.setText("•");
        boton_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_salirMouseExited(evt);
            }
        });
        zona_pantalla.add(boton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pantalla_pequena.setEditable(false);
        pantalla_pequena.setBackground(new java.awt.Color(241, 253, 251));
        pantalla_pequena.setColumns(20);
        pantalla_pequena.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pantalla_pequena.setForeground(new java.awt.Color(51, 61, 73));
        pantalla_pequena.setRows(5);
        pantalla_pequena.setBorder(null);
        pantalla_pequena.setCaretColor(new java.awt.Color(204, 255, 255));
        pantalla_pequena.setFocusable(false);
        pantalla_pequena.setHighlighter(null);
        pantalla_pequena.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(pantalla_pequena);

        zona_pantalla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, 20));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pantalla_grande.setAlignmentX(JTextArea.RIGHT_ALIGNMENT);
        pantalla_grande.setEditable(false);
        pantalla_grande.setBackground(new java.awt.Color(241, 253, 251));
        pantalla_grande.setColumns(20);
        pantalla_grande.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        pantalla_grande.setForeground(new java.awt.Color(51, 61, 73));
        pantalla_grande.setRows(5);
        pantalla_grande.setAutoscrolls(false);
        pantalla_grande.setBorder(null);
        pantalla_grande.setCaretColor(new java.awt.Color(204, 255, 255));
        pantalla_grande.setFocusable(false);
        pantalla_grande.setHighlighter(null);
        pantalla_grande.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(pantalla_grande);

        zona_pantalla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, 40));

        mover_ventana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mover_ventana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mover_ventanaMouseDragged(evt);
            }
        });
        mover_ventana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mover_ventanaMousePressed(evt);
            }
        });
        zona_pantalla.add(mover_ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 240, 20));

        getContentPane().add(zona_pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 334, 130));

        zona_botones.setBackground(new java.awt.Color(255, 255, 255));

        boton_resta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        boton_resta.setForeground(new java.awt.Color(53, 64, 68));
        boton_resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton.png"))); // NOI18N
        boton_resta.setText("-");
        boton_resta.setContentAreaFilled(false);
        boton_resta.setFocusable(false);
        boton_resta.setHideActionText(true);
        boton_resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_resta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton_oscuro_2.png"))); // NOI18N
        boton_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_restaActionPerformed(evt);
            }
        });

        boton_borrar_todo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_borrar_todo.setForeground(new java.awt.Color(53, 64, 68));
        boton_borrar_todo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton.png"))); // NOI18N
        boton_borrar_todo.setText("C");
        boton_borrar_todo.setContentAreaFilled(false);
        boton_borrar_todo.setFocusable(false);
        boton_borrar_todo.setHideActionText(true);
        boton_borrar_todo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_borrar_todo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton_oscuro_2.png"))); // NOI18N
        boton_borrar_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrar_todoActionPerformed(evt);
            }
        });

        boton_borrar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_borrar2.setForeground(new java.awt.Color(53, 64, 68));
        boton_borrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton.png"))); // NOI18N
        boton_borrar2.setText("<-");
        boton_borrar2.setContentAreaFilled(false);
        boton_borrar2.setFocusable(false);
        boton_borrar2.setHideActionText(true);
        boton_borrar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_borrar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton_oscuro_2.png"))); // NOI18N
        boton_borrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrar2ActionPerformed(evt);
            }
        });

        boton_porcentaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_porcentaje.setForeground(new java.awt.Color(53, 64, 68));
        boton_porcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton.png"))); // NOI18N
        boton_porcentaje.setText("%");
        boton_porcentaje.setContentAreaFilled(false);
        boton_porcentaje.setFocusable(false);
        boton_porcentaje.setHideActionText(true);
        boton_porcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_porcentaje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton_oscuro_2.png"))); // NOI18N
        boton_porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_porcentajeActionPerformed(evt);
            }
        });

        boton_division.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_division.setForeground(new java.awt.Color(53, 64, 68));
        boton_division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton.png"))); // NOI18N
        boton_division.setText("/");
        boton_division.setContentAreaFilled(false);
        boton_division.setFocusable(false);
        boton_division.setHideActionText(true);
        boton_division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_division.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton_oscuro_2.png"))); // NOI18N
        boton_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_divisionActionPerformed(evt);
            }
        });

        boton_igual.setBackground(new java.awt.Color(255, 255, 255));
        boton_igual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_igual.setForeground(new java.awt.Color(255, 255, 255));
        boton_igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icono_igual_modo_oscuro.png"))); // NOI18N
        boton_igual.setText("=");
        boton_igual.setContentAreaFilled(false);
        boton_igual.setFocusable(false);
        boton_igual.setHideActionText(true);
        boton_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_igual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icono_igual_modo_osucuro_rollover.png"))); // NOI18N
        boton_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_igualActionPerformed(evt);
            }
        });

        boton_multiplicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_multiplicacion.setForeground(new java.awt.Color(53, 64, 68));
        boton_multiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton.png"))); // NOI18N
        boton_multiplicacion.setText("X");
        boton_multiplicacion.setContentAreaFilled(false);
        boton_multiplicacion.setFocusable(false);
        boton_multiplicacion.setHideActionText(true);
        boton_multiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_multiplicacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton_oscuro_2.png"))); // NOI18N
        boton_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_multiplicacionActionPerformed(evt);
            }
        });

        boton_suma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_suma.setForeground(new java.awt.Color(53, 64, 68));
        boton_suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton.png"))); // NOI18N
        boton_suma.setText("+");
        boton_suma.setContentAreaFilled(false);
        boton_suma.setFocusable(false);
        boton_suma.setHideActionText(true);
        boton_suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_suma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icono_boton_oscuro_2.png"))); // NOI18N
        boton_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sumaActionPerformed(evt);
            }
        });

        programador.setText("Roger Vergara 2020");

        boton_siete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_siete.setForeground(new java.awt.Color(53, 64, 68));
        boton_siete.setText("7");
        boton_siete.setContentAreaFilled(false);
        boton_siete.setFocusable(false);
        boton_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sieteActionPerformed(evt);
            }
        });

        boton_nueve.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_nueve.setForeground(new java.awt.Color(53, 64, 68));
        boton_nueve.setText("9");
        boton_nueve.setContentAreaFilled(false);
        boton_nueve.setFocusable(false);
        boton_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nueveActionPerformed(evt);
            }
        });

        boton_ocho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_ocho.setForeground(new java.awt.Color(53, 64, 68));
        boton_ocho.setText("8");
        boton_ocho.setContentAreaFilled(false);
        boton_ocho.setFocusable(false);
        boton_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ochoActionPerformed(evt);
            }
        });

        boton_seis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_seis.setForeground(new java.awt.Color(53, 64, 68));
        boton_seis.setText("6");
        boton_seis.setContentAreaFilled(false);
        boton_seis.setFocusable(false);
        boton_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_seisActionPerformed(evt);
            }
        });

        boton_tres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_tres.setForeground(new java.awt.Color(53, 64, 68));
        boton_tres.setText("3");
        boton_tres.setContentAreaFilled(false);
        boton_tres.setFocusable(false);
        boton_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_tresActionPerformed(evt);
            }
        });

        boton_cinco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_cinco.setForeground(new java.awt.Color(53, 64, 68));
        boton_cinco.setText("5");
        boton_cinco.setContentAreaFilled(false);
        boton_cinco.setFocusable(false);
        boton_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cincoActionPerformed(evt);
            }
        });

        boton_cuatro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_cuatro1.setForeground(new java.awt.Color(53, 64, 68));
        boton_cuatro1.setText("4");
        boton_cuatro1.setContentAreaFilled(false);
        boton_cuatro1.setFocusable(false);
        boton_cuatro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cuatro1ActionPerformed(evt);
            }
        });

        boton_punto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_punto.setForeground(new java.awt.Color(53, 64, 68));
        boton_punto.setText(".");
        boton_punto.setContentAreaFilled(false);
        boton_punto.setFocusable(false);
        boton_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_puntoActionPerformed(evt);
            }
        });

        boton_dos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_dos.setForeground(new java.awt.Color(53, 64, 68));
        boton_dos.setText("2");
        boton_dos.setContentAreaFilled(false);
        boton_dos.setFocusable(false);
        boton_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_dosActionPerformed(evt);
            }
        });

        boton_uno1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_uno1.setForeground(new java.awt.Color(53, 64, 68));
        boton_uno1.setText("1");
        boton_uno1.setContentAreaFilled(false);
        boton_uno1.setFocusable(false);
        boton_uno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_uno1ActionPerformed(evt);
            }
        });

        boton_cero1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_cero1.setForeground(new java.awt.Color(53, 64, 68));
        boton_cero1.setText("0");
        boton_cero1.setContentAreaFilled(false);
        boton_cero1.setFocusable(false);
        boton_cero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cero1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zona_botonesLayout = new javax.swing.GroupLayout(zona_botones);
        zona_botones.setLayout(zona_botonesLayout);
        zona_botonesLayout.setHorizontalGroup(
            zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zona_botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(zona_botonesLayout.createSequentialGroup()
                        .addComponent(boton_borrar_todo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton_borrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(boton_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(zona_botonesLayout.createSequentialGroup()
                        .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_cuatro1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_uno1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_cero1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(zona_botonesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(zona_botonesLayout.createSequentialGroup()
                                        .addComponent(boton_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(zona_botonesLayout.createSequentialGroup()
                                        .addComponent(boton_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(zona_botonesLayout.createSequentialGroup()
                                        .addComponent(boton_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(zona_botonesLayout.createSequentialGroup()
                                .addComponent(boton_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(10, 10, 10)
                .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_division, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zona_botonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(programador)
                .addGap(115, 115, 115))
        );
        zona_botonesLayout.setVerticalGroup(
            zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zona_botonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_borrar_todo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_borrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_division, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_cuatro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_uno1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(zona_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_cero1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(programador)
                .addContainerGap())
        );

        getContentPane().add(zona_botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 334, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_uno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_uno1ActionPerformed
        Generar_Texto("1");
    }//GEN-LAST:event_boton_uno1ActionPerformed

    private void boton_modo_oscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modo_oscuroActionPerformed
        if (modo_oscuro == true) {
            this.zona_pantalla.setBackground(Color.decode("#152640"));
            this.zona_botones.setBackground(Color.decode("#253652"));
            this.pantalla_pequena.setBackground(Color.decode("#152640"));
            this.pantalla_grande.setBackground(Color.decode("#152640"));
            this.programador.setForeground(Color.decode("#00d89d"));
            this.pantalla_pequena.setForeground(Color.decode("#00d89d"));
            this.pantalla_grande.setForeground(Color.decode("#00d89d"));

            //botones especiales
            cambiar_botones_especiales_modo_oscuro(boton_borrar_todo);
            cambiar_botones_especiales_modo_oscuro(boton_borrar2);
            cambiar_botones_especiales_modo_oscuro(boton_suma);
            cambiar_botones_especiales_modo_oscuro(boton_resta);
            cambiar_botones_especiales_modo_oscuro(boton_multiplicacion);
            cambiar_botones_especiales_modo_oscuro(boton_division);
            cambiar_botones_especiales_modo_oscuro(boton_porcentaje);

            //Boton igual
            boton_igual.setForeground(Color.decode("152640"));

            //botones numericos
            cambiar_botones_numeros_modo_oscuro(boton_cero1);
            cambiar_botones_numeros_modo_oscuro(boton_punto);
            cambiar_botones_numeros_modo_oscuro(boton_uno1);
            cambiar_botones_numeros_modo_oscuro(boton_dos);
            cambiar_botones_numeros_modo_oscuro(boton_tres);
            cambiar_botones_numeros_modo_oscuro(boton_cuatro1);
            cambiar_botones_numeros_modo_oscuro(boton_cinco);
            cambiar_botones_numeros_modo_oscuro(boton_seis);
            cambiar_botones_numeros_modo_oscuro(boton_siete);
            cambiar_botones_numeros_modo_oscuro(boton_ocho);
            cambiar_botones_numeros_modo_oscuro(boton_nueve);

            this.boton_borrar_todo.setForeground(Color.decode("#00d89d"));
            this.boton_modo_oscuro.setIcon(new ImageIcon(getClass().getResource("/Images/Barra_de_noche.png")));
            modo_oscuro = false;
        } else {
            dispose();
            vista v = new vista();
            v.setVisible(true);

        }
    }//GEN-LAST:event_boton_modo_oscuroActionPerformed

    private void boton_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_boton_salirMouseClicked

    private void boton_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_minimizarMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_boton_minimizarMouseClicked

    private void boton_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_salirMouseEntered
        this.boton_salir.setForeground(Color.decode("#A50100"));
    }//GEN-LAST:event_boton_salirMouseEntered

    private void boton_minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_minimizarMouseExited
        this.boton_minimizar.setForeground(Color.decode("#FFCC66"));
    }//GEN-LAST:event_boton_minimizarMouseExited

    private void boton_minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_minimizarMouseEntered
        this.boton_minimizar.setForeground(Color.decode("#FF7E0F"));
    }//GEN-LAST:event_boton_minimizarMouseEntered

    private void boton_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_salirMouseExited
        this.boton_salir.setForeground(Color.decode("#FF3333"));
    }//GEN-LAST:event_boton_salirMouseExited

    private void boton_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_dosActionPerformed
        Generar_Texto("2");
    }//GEN-LAST:event_boton_dosActionPerformed

    private void boton_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_tresActionPerformed
        Generar_Texto("3");
    }//GEN-LAST:event_boton_tresActionPerformed

    private void boton_cero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cero1ActionPerformed
        Generar_Texto("0");
    }//GEN-LAST:event_boton_cero1ActionPerformed

    private void boton_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_puntoActionPerformed
        Generar_Texto(".");
    }//GEN-LAST:event_boton_puntoActionPerformed

    private void boton_cuatro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cuatro1ActionPerformed
        Generar_Texto("4");
    }//GEN-LAST:event_boton_cuatro1ActionPerformed

    private void boton_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cincoActionPerformed
        Generar_Texto("5");
    }//GEN-LAST:event_boton_cincoActionPerformed

    private void boton_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_seisActionPerformed
        Generar_Texto("6");
    }//GEN-LAST:event_boton_seisActionPerformed

    private void boton_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sieteActionPerformed
        Generar_Texto("7");
    }//GEN-LAST:event_boton_sieteActionPerformed

    private void boton_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ochoActionPerformed
        Generar_Texto("8");
    }//GEN-LAST:event_boton_ochoActionPerformed

    private void boton_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nueveActionPerformed
        Generar_Texto("9");
    }//GEN-LAST:event_boton_nueveActionPerformed

    private void boton_borrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_borrar2ActionPerformed
        String ultimo_digito_pantalla_grande = this.pantalla_grande.getText();
        String ultimo_digito_pantalla_pequena = this.pantalla_pequena.getText();

        if (ultimo_digito_pantalla_grande.length() >= 1
                && ultimo_digito_pantalla_pequena.length() >= 1) {

            int anterior_1 = ultimo_digito_pantalla_grande.length() - 1;
            int _final_1 = ultimo_digito_pantalla_grande.length();

            int anterior_2 = ultimo_digito_pantalla_pequena.length() - 1;
            int _final_2 = ultimo_digito_pantalla_pequena.length();

            this.pantalla_grande.replaceRange(null, anterior_1, _final_1);
            this.pantalla_pequena.replaceRange(null, anterior_2, _final_2);

        }
    }//GEN-LAST:event_boton_borrar2ActionPerformed

    private void mover_ventanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mover_ventanaMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_mover_ventanaMousePressed

    private void mover_ventanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mover_ventanaMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_mover_ventanaMouseDragged

    private void boton_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sumaActionPerformed
        primer_dato = Float.parseFloat(pantalla_grande.getText());
        operador = "+";
        this.pantalla_grande.setText(null);
        this.pantalla_pequena.setText(null);
    }//GEN-LAST:event_boton_sumaActionPerformed

    private void boton_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_restaActionPerformed
        primer_dato = Float.parseFloat(pantalla_grande.getText());
        operador = "-";
        this.pantalla_grande.setText(null);
        this.pantalla_pequena.setText(null);
    }//GEN-LAST:event_boton_restaActionPerformed

    private void boton_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_multiplicacionActionPerformed
        primer_dato = Float.parseFloat(pantalla_grande.getText());
        operador = "*";
        this.pantalla_grande.setText(null);
        this.pantalla_pequena.setText(null);
    }//GEN-LAST:event_boton_multiplicacionActionPerformed

    private void boton_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_divisionActionPerformed
        primer_dato = Float.parseFloat(pantalla_grande.getText());
        operador = "/";
        this.pantalla_grande.setText(null);
        this.pantalla_pequena.setText(null);
    }//GEN-LAST:event_boton_divisionActionPerformed

    private void boton_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_igualActionPerformed
        try {
            segundo_dato = Float.parseFloat(this.pantalla_grande.getText());
            switch (operador) {
                case "+": {
                    resultado = primer_dato + segundo_dato;
                    if (resultado % 2 == 0) {
                        int cambio = (int) resultado;
                        this.pantalla_grande.setText(Integer.toString(cambio));
                        this.pantalla_pequena.setText(Integer.toString(cambio));
                    } else {
                        this.pantalla_grande.setText(Float.toString(resultado));
                        this.pantalla_pequena.setText(Float.toString(resultado));
                    }
                }
                break;
                case "-": {
                    resultado = primer_dato - segundo_dato;
                    if (resultado % 2 == 0) {
                        int cambio = (int) resultado;
                        this.pantalla_grande.setText(Integer.toString(cambio));
                        this.pantalla_pequena.setText(Integer.toString(cambio));
                    } else {
                        this.pantalla_grande.setText(Float.toString(resultado));
                        this.pantalla_pequena.setText(Float.toString(resultado));
                    }
                }
                break;
                case "*": {
                    resultado = primer_dato * segundo_dato;
                    if (resultado % 2 == 0) {
                        int cambio = (int) resultado;
                        this.pantalla_grande.setText(Integer.toString(cambio));
                        this.pantalla_pequena.setText(Integer.toString(cambio));
                    } else {
                        this.pantalla_grande.setText(Float.toString(resultado));
                        this.pantalla_pequena.setText(Float.toString(resultado));
                    }
                }
                break;
                case "/": {
                    resultado = primer_dato / segundo_dato;
                    if (resultado % 2 == 0) {
                        int cambio = (int) resultado;
                        this.pantalla_grande.setText(Integer.toString(cambio));
                        this.pantalla_pequena.setText(Integer.toString(cambio));
                    } else {
                        this.pantalla_grande.setText(Float.toString(resultado));
                        this.pantalla_pequena.setText(Float.toString(resultado));
                    }
                }
                break;
                case "%": {
                    resultado = primer_dato % segundo_dato;
                    if (resultado % 2 == 0) {
                        int cambio = (int) resultado;
                        this.pantalla_grande.setText(Integer.toString(cambio));
                        this.pantalla_pequena.setText(Integer.toString(cambio));
                    } else {
                        this.pantalla_grande.setText(Float.toString(resultado));
                        this.pantalla_pequena.setText(Float.toString(resultado));
                    }
                }
                break;
            }
        } catch (Exception e) {
            primer_dato = 0;
            this.pantalla_grande.setText("0");
            this.pantalla_pequena.setText("0");
        }
    }//GEN-LAST:event_boton_igualActionPerformed

    private void boton_borrar_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_borrar_todoActionPerformed
        this.pantalla_grande.setText(null);
        this.pantalla_pequena.setText(null);
    }//GEN-LAST:event_boton_borrar_todoActionPerformed

    private void boton_porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_porcentajeActionPerformed
        primer_dato = Float.parseFloat(pantalla_grande.getText());
        operador = "%";
        this.pantalla_grande.setText(null);
        this.pantalla_pequena.setText(null);
    }//GEN-LAST:event_boton_porcentajeActionPerformed

    public void cambiar_botones_especiales_modo_oscuro(JButton boton) {
        boton.setIcon(new ImageIcon(getClass().getResource("/Images/Icono_Boton_Noche.png")));
        boton.setRolloverIcon(new ImageIcon(getClass().getResource("/Images/Icono_boton_noche_oscuro_2.png")));
        boton.setForeground(Color.decode("#00d89d"));
    }

    public void cambiar_botones_numeros_modo_oscuro(JButton boton) {
        boton.setBackground(Color.decode("#253652"));
        boton.setForeground(Color.decode("#9db1ba"));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_borrar2;
    private javax.swing.JButton boton_borrar_todo;
    private javax.swing.JButton boton_cero1;
    private javax.swing.JButton boton_cinco;
    private javax.swing.JButton boton_cuatro1;
    private javax.swing.JButton boton_division;
    private javax.swing.JButton boton_dos;
    private javax.swing.JButton boton_igual;
    private javax.swing.JLabel boton_minimizar;
    private javax.swing.JButton boton_modo_oscuro;
    private javax.swing.JButton boton_multiplicacion;
    private javax.swing.JButton boton_nueve;
    private javax.swing.JButton boton_ocho;
    private javax.swing.JButton boton_porcentaje;
    private javax.swing.JButton boton_punto;
    private javax.swing.JButton boton_resta;
    private javax.swing.JLabel boton_salir;
    private javax.swing.JButton boton_seis;
    private javax.swing.JButton boton_siete;
    private javax.swing.JButton boton_suma;
    private javax.swing.JButton boton_tres;
    private javax.swing.JButton boton_uno1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mover_ventana;
    private javax.swing.JTextArea pantalla_grande;
    private javax.swing.JTextArea pantalla_pequena;
    private javax.swing.JLabel programador;
    private javax.swing.JPanel zona_botones;
    private javax.swing.JPanel zona_pantalla;
    // End of variables declaration//GEN-END:variables
}
